### ISSUE TITLE
Is it possible to change the category of the torrent?

### ISSUE THREAD

**Issue by adamryczkowski** [fedarovich/qbittorrent-cli#1]
I would like to be able to change the category (or otherwise tag) a torrent once the script downloaded it from the torrent box. 

Is it possible at all using `qbittorrent-cli`?

Great job, by the way. The client has a very professional feel and a good API. Thank you very much for sharing it.

**Comment by adamryczkowski** [comment]
I use ```$ qbt --version
0.10.18151.1
```

**Comment by fedarovich** [comment]
Yes, you can change the category by the following command:
```
qbt torrent category <HASH> --set <CATEGORY>
```
where `<HASH>` is the partial hash of your torrent (usually 4-8 first characters is enough) and `<CATEGORY>` is the category name. If the category does not exist it will be created automatically.

For example, to category `Linux` to the torrent with the hash starting from `3ab528` you should run:
```
qbt torrent category 3ab528 --set Linux
```

Alas, it is not possible to work with tags in the current version, because qBittorrent provides no WebAPI for tag manipulation. I hope, they will support it one day.

**Comment by adamryczkowski** [comment]
Yes, it works. Thank you very much for the response and the great program!
