### ISSUE TITLE
Hash argument is bugged

### ISSUE THREAD

**Issue by foxi69** [fedarovich/qbittorrent-cli#102]
`qbt torrent list --url $WebURL $Hash`
Specify --help for a list of available options and commands.
Unrecognized command or argument '98d6f7ccbf7e211d43668ea0a2a1cc86c5b1c280'

`qbt torrent list --url $WebURL --hash $Hash`
-> Work 

`(qbt torrent list --url $WebURL --hash $Hash -F json | ConvertFrom-Json).state`
Unrecognized option '--hash'

**Comment by sir-wilhelm** [comment]
What version are you running and on what system?

The first command does not work because it's missing the `--hash ` or `-H` (as specified in `qbt torrent list --help`). 
The second command works, and looks fine.

I can get the 3rd command to work in pwsh on my end, but in your example it's missing the opening `(`, it should be:
```powershell
(qbt torrent list --url $WebURL --hash $Hash -F json | ConvertFrom-Json).state
```

**Comment by sir-wilhelm** [comment]
I won't know exactly what is wrong w/o seeing the contents of the script, but the double quoted strings might be the issue.

Does it work correctly if you drop the internal `'`s? 
Replacing
`"'` with `"` and 
`'"` with `"` in all of the `-Parameter` values?

**Comment by sir-wilhelm** [comment]
Oh I see the disconnect.

When calling `qbt torrent list` you need to provide `-H` or `--hash`, but it's not required for `tracker` (see `qbt torrent tracker list --help`).

```powershell
$Trackers = (qbt torrent tracker list --url $WebURL $Hash -F json | ConvertFrom-Json).url
```

if you use that it'll give you an array of all the tracker URLs for the provided torrent/hash.
