### ISSUE TITLE
"Key not valid for use in specific state"

### ISSUE THREAD

**Issue by Brodieman** [fedarovich/qbittorrent-cli#75]
I have been using this for quite some time and love it (thank you!).

All of a sudden it was not working.  I went to check some things and whenever I run any command (even qbt torrent list) I get the error "Key not valid for use in specified state.".

**Comment by fedarovich** [comment]
Hi,

Could you provide some additional information:
- Your operating system
- Version of qBittorrent

Additionally, could you run any command producing this error with parameter `--print-stacktrace` and post the output here

**Comment by Brodieman** [comment]
Windows 10 22H2
QBit 4.4.5 64bit
QBitCLI 1.7.22220.1

Ran with that parameter and go the same result
![image](https://user-images.githubusercontent.com/13592675/201339786-4fcff727-60a5-4c4e-b8f8-6fb07a1c460b.png)

**Comment by fedarovich** [comment]
Hm, it's more likely the issue with your system rather than with qbt. This error message is related to some issue with X509 certificates, but they are not used by qbt (except corresponding settings command).

You can try to do the following steps, it might help:
1. Navigate to `C:\Users\<username>\AppData\Roaming\Microsoft`
2. Rename the Crypto folder to CryptoOld
3. Try running qbt again

**Comment by Brodieman** [comment]
I was not able to rename it but I was able to delete it.  I did that and restarted, the folder was recreated and I get the same message.  If you don't think it's with QBT CLI I will start looking around

**Comment by Brodieman** [comment]
Looks like you are right. SFC is showing errors. Everything else is working fine so I didn't look. Thanks and sorry.

**Comment by Brodieman** [comment]
I was finally able to figure this out.  It WAS the CLI program but not a bug.  I did "qbt network credentials clear" and then resetup everything and it works now
